[2025-09-28T07:03:30.689+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/lic_processing_dag.py
[2025-09-28T07:03:30.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lic_processing_dag.py for tasks to queue
[2025-09-28T07:03:30.699+0000] {logging_mixin.py:188} INFO - [2025-09-28T07:03:30.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lic_processing_dag.py
[2025-09-28T07:03:30.746+0000] {logging_mixin.py:188} INFO - [2025-09-28T07:03:30.738+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lic_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lic_processing_dag.py", line 10, in <module>
    from utils.pdf_extractor import LICReceiptExtractor, validate_financial_year
  File "/opt/airflow/dags/utils/pdf_extractor.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2025-09-28T07:03:30.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lic_processing_dag.py
[2025-09-28T07:03:30.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lic_processing_dag.py took 0.091 seconds
